export const ACTION_TYPES = {
  LOAD_TODOS: 'LOAD_TODOS',
  ADD_TODO: 'ADD_TODO',
  TOGGLE_COMPLETE_TODO: 'TOGGLE_COMPLETE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  TODO_EDIT_MODE: 'TODO_EDIT_MODE',
  EDIT_TODO: 'EDIT_TODO',

  LOAD_USERS: 'LOAD_USERS',
  ADD_USER: 'ADD_USER',
}